#pragma once

#define NEKO_ANONYMOUS_NAME_CAT(A, B) NEKO_ANONYMOUS_NAME_CAT_IMPL(A, B)
#define NEKO_ANONYMOUS_NAME_CAT_IMPL(A, B) A##B

#ifdef __COUNTER__
#define NEKO_ANONYMOUS_NAME(STR) NEKO_ANONYMOUS_NAME_CAT(STR, __COUNTER__)
#else
#define NEKO_ANONYMOUS_NAME(STR) NEKO_ANONYMOUS_NAME_CAT(STR, __LINE__)
#endif
